In [3]:
import numpy as np

In [7]:
def fuzzy_union(A, B):
    return np.maximum(A, B)

In [9]:
def fuzzy_intersection(A, B):
    return np.minimum(A, B)

In [11]:
def fuzzy_complement(A):
    return 1 - A

In [13]:
def fuzzy_difference(A, B):
    return np.maximum(A, 1 - B)

In [15]:
def cartesian_product(A, B):
    return np.outer(A, B)

In [17]:
def max_min_composition(R, S):
    return np.max(np.minimum.outer(R, S), axis=1)

In [19]:
A = np.array([0.2, 0.4, 0.6, 0.8])   # Fuzzy set A
B = np.array([0.3, 0.5, 0.7, 0.9])   # Fuzzy set B


In [21]:
union_result = fuzzy_union(A, B)
intersection_result = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
difference_result = fuzzy_difference(A, B)


In [23]:
print("Union:", union_result)
print("Intersection:", intersection_result)
print("Complement of A:", complement_A)
print("Difference:", difference_result)

Union: [0.3 0.5 0.7 0.9]
Intersection: [0.2 0.4 0.6 0.8]
Complement of A: [0.8 0.6 0.4 0.2]
Difference: [0.7 0.5 0.6 0.8]


In [25]:
R = np.array([0.2, 0.5, 0.4])   # Fuzzy relation R
S = np.array([0.6, 0.3, 0.7])   # Fuzzy relation S

In [27]:
cartesian_result = cartesian_product(R, S)

In [29]:
composition_result = max_min_composition(R, S)

In [31]:
print("\nCartesian product of R and S:")
print(cartesian_result)


Cartesian product of R and S:
[[0.12 0.06 0.14]
 [0.3  0.15 0.35]
 [0.24 0.12 0.28]]


In [33]:
print("\nMax-Min composition of R and S:")
print(composition_result)


Max-Min composition of R and S:
[0.2 0.5 0.4]
