In [1]:
import numpy as np
import random

In [3]:
# Distance Matrix (Distances Between Cities)

distance_matrix = np.array([
    [0, 10, 15, 20],
    [10, 0, 35, 25],
    [15, 35, 0, 30],
    [20, 25, 30, 0]
])

print(distance_matrix)

[[ 0 10 15 20]
 [10  0 35 25]
 [15 35  0 30]
 [20 25 30  0]]


In [5]:
# Parameters for Ant Colony Optimization

num_ants = 10
num_iterations = 50

evaporation_rate = 0.5

pheromone_constant = 1.0
heuristic_constant = 1.0

# Number of Cities
num_cities = len(distance_matrix)

# Initialize Pheromone Matrix
pheromone = np.ones((num_cities, num_cities))

# Initialize Visibility Matrix
visibility = np.zeros((num_cities, num_cities))

for i in range(num_cities):
    for j in range(num_cities):

        if distance_matrix[i][j] != 0:
            visibility[i][j] = 1 / distance_matrix[i][j]

print("Pheromone Matrix:")
print(pheromone)

print("\nVisibility Matrix:")
print(visibility)

Pheromone Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Visibility Matrix:
[[0.         0.1        0.06666667 0.05      ]
 [0.1        0.         0.02857143 0.04      ]
 [0.06666667 0.02857143 0.         0.03333333]
 [0.05       0.04       0.03333333 0.        ]]


In [7]:
# ACO Algorithm

for iteration in range(num_iterations):

    ant_routes = []

    for ant in range(num_ants):

        current_city = random.randint(0, num_cities - 1)

        visited_cities = [current_city]

        route = [current_city]

        while len(visited_cities) < num_cities:

            probabilities = []

            for city in range(num_cities):

                if city not in visited_cities:

                    pheromone_value = pheromone[current_city][city]

                    visibility_value = visibility[current_city][city]

                    probability = (
                        (pheromone_value ** pheromone_constant)
                        *
                        (visibility_value ** heuristic_constant)
                    )

                    probabilities.append((city, probability))

            probabilities = sorted(
                probabilities,
                key=lambda x: x[1],
                reverse=True
            )

            selected_city = probabilities[0][0]

            route.append(selected_city)

            visited_cities.append(selected_city)

            current_city = selected_city

        ant_routes.append(route)

    # Update Pheromone Levels

    delta_pheromone = np.zeros((num_cities, num_cities))

    for route in ant_routes:

        for i in range(len(route) - 1):

            city_a = route[i]

            city_b = route[i + 1]

            delta_pheromone[city_a][city_b] += (
                1 / distance_matrix[city_a][city_b]
            )

            delta_pheromone[city_b][city_a] += (
                1 / distance_matrix[city_a][city_b]
            )

    pheromone = (
        (1 - evaporation_rate) * pheromone
        +
        delta_pheromone
    )

print("ACO Training Completed")

ACO Training Completed


In [9]:
# Function to Calculate Route Distance

def calculate_distance(route):

    total_distance = 0

    for i in range(num_cities):

        total_distance += distance_matrix[
            route[i]
        ][
            route[(i + 1) % num_cities]
        ]

    return total_distance


# Find Best Route

best_route = min(
    ant_routes,
    key=calculate_distance
)

shortest_distance = calculate_distance(best_route)

print("Best Route:", best_route)

print("Shortest Distance:", shortest_distance)

Best Route: [0, 1, 3, 2]
Shortest Distance: 80
